#! /usr/bin/env bash

# Check for the bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-paulocarlos-teste"
    exit 1
fi

BUCKET_NAME=$1

echo aws s3api create-bucket --bucket $BUCKET_NAME

aws s3api create-bucket --bucket $BUCKET_NAME \
--query 'Location' \
--output text | sed 's|^.*//||'


