#!/usr/bin/env bash

echo "== put_objects =="

# Exit immediately if a command exits with a non-zero status
set -e

# Script: Criar arquivo de teste para gerar test files
OUTPUT_DIR="/mnt/c/Users/paulo/Documents/Cursos/aws/aws-exemples/files-aws-put-5"

# lets create output folder
echo "Criando pasta: $OUTPUT_DIR"

# remove folder if it already exists
rm -r $OUTPUT_DIR

mkdir -p $OUTPUT_DIR
echo "Pasta criada!"

# generate a random number
# to determine how many files to create

NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<$NUM_FILES; i++)); do
  # Generate a random filename

  FILENAME="$OUTPUT_DIR/file_$i.txt"

  # Generate random data and write it to the file

  dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) > /dev/null

done

tree $OUTPUT_DIR
