apiVersion: v1
kind: Pod
metadata:
  name: powershell-aws-final
spec:
  containers:
  - name: main-container
    image: alpine:latest
    stdin: true
    tty: true
    command: ["/bin/sh", "-c"]
    args:
      - |
        # 1. Dependências e PowerShell
        apk update
        apk add --no-cache \
            ca-certificates less ncurses-terminfo-base krb5-libs libgcc \
            libintl libssl3 libstdc++ tzdata userspace-rcu zlib icu-libs \
            curl unzip bash gcompat

        apk add --no-cache powershell --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community

        # 2. AWS CLI v2
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        ./aws/install
        rm -rf awscliv2.zip aws/

        # 3. AWS Tools + Módulo S3 (Já deixa o CRUD pronto)
        pwsh -Command "
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted;
          Install-Module -Name AWS.Tools.Installer -Force -Scope CurrentUser;
          Install-AWSToolsModule S3 -Force -Scope CurrentUser
        "

        echo "Tudo pronto! PowerShell e S3 preparados."
        sleep infinity